# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('fathers_name', models.CharField(max_length=40, null=True)),
                ('mothers_name', models.CharField(max_length=40, null=True)),
                ('nationality', models.CharField(max_length=40, null=True)),
                ('emip_marks', models.BigIntegerField(default=None)),
                ('emip_grade', models.CharField(max_length=3, null=True)),
                ('emwe_marks', models.BigIntegerField(default=None, null=True)),
                ('emwe_grade', models.CharField(max_length=3, null=True)),
                ('esas_marks', models.BigIntegerField(default=None)),
                ('esas_grade', models.CharField(max_length=3, null=True)),
                ('eict_marks', models.BigIntegerField(default=None)),
                ('eict_grade', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
