# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eemp_marks',
            field=models.IntegerField(default=0),
        ),
    ]
