# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_student_eemp_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eemp_grade',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
