# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_student_eemp_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emmp_grade',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emmp_marks',
            field=models.IntegerField(default=0),
        ),
    ]
