# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180130_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_address',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
